name: node_preamble
author: Michael Bullington <mikebullingtn@gmail.com>
homepage: https://github.com/mbullington/node_preamble.dart
version: 1.1.0
description: Better node.js preamble for dart2js, use it in your build system.
